CREATE TABLE `news` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `title` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '标题',
  `content` text COLLATE utf8mb4_unicode_ci COMMENT '内容',
  `author` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '作者',
  `time` datetime DEFAULT NULL COMMENT '发布时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=38 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE `plank` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `title` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '标题',
  `content` text COLLATE utf8mb4_unicode_ci COMMENT '内容',
  `author` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '作者',
  `time` datetime DEFAULT NULL COMMENT '发布时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE `user` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `username` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '用户名',
  `password` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '密码',
  `nick_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '昵称',
  `age` int(11) DEFAULT NULL COMMENT '年龄',
  `sex` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '性别',
  `address` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '地址',
  `role` int(11) DEFAULT NULL COMMENT '角色，1：管理员，2：普通用户',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=26 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='用户信息表';

INSERT INTO `news` (`id`, `title`, `content`, `author`, `time`) VALUES ('25','副校长傅凤龙教授带队赴河源职业技术学院和深圳信息职业技术学院交流学习','<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;12月8日-9日，副校长傅凤龙教授带队赴河源职业技术学院和深圳信息职业技术学院进行交流学习，我校管理学院相关负责人、各专业教研室主任陪同交流。<br/></p><p><br/></p><p>&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;8日上午，傅凤龙带队赴河源职业技术学院工商管理学院交流学习，受到河源职业技术学院副校长袁光华的热情接待。在工商管理学院领导的陪同下，傅凤龙一行参观了旅游管理专业的烹饪实训室、茶艺实训室、酒吧实训室等场地。<br/></p><p><br/></p><p>&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;座谈会上，双方围绕高水平专业群建设、技能大赛、专业设置、师资队伍建设、课程建设和科研与社会服务等内容进行了深入探讨交流。会后，双方教研室主任进行了一对一的深度交流。<br/></p><p><img src="https://s4.ax1x.com/2021/12/17/TkivEq.jpg" style="max-width:100%;" contenteditable="false"/></p>','管理员','2021-12-14 10:38:59');
INSERT INTO `news` (`id`, `title`, `content`, `author`, `time`) VALUES ('26','我校与广东香美农业科技公司举行共建校企合作产学研创新实践合作基地签约仪式','<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;为深入贯彻落实党中央全面推进乡村振兴战略要求，推进产学研合作，12月8日下午，我校与广东香美农业科技公司举行共建校企合作产学研创新实践合作基地签约仪式，仪式由陆河县河口镇委书记余代治主持，陆河县政府办公室副主任彭新艳、广东香美农业科技公司董事长陈佳明、我校科研处、教务处、成教处、人文学院、广东省教育厅普通高校人文社科重点研究基地“数字+”乡村振兴创新传播研究基地等相关负责人出席签约仪式。<br/></p><p><br/></p><p>&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;<span style="color: var(--el-text-color-regular);">会上，陆河县政府办公室副主任彭新艳首先代表县政府向项目正式签约表示热烈的祝贺，对出席签约仪式的领导嘉宾表示衷心的感谢。他表示，目前河口镇大力发展沉香产业，通过成立种养专业合作社和引进香美公司，实现规模化、专业化生产，现已成为陆河县特色农业产业之一。此次产学研创新实践基地的合作签约是我县企业和高等院校谋求产学研紧密结合的一次重要实践，对进一步探索高校科技教育资源服务我县经济社会发展、提高企业自主创新能力、促进产业升级、实现高质量发展具有重要的意义。</span><br/></p><p><br/></p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;科研处处长王思荣在致辞中介绍了我校的基本情况和发展历史，表示希望以此次合作为契机，充分发挥校方的人才与智力优势，不断深化与广东香美科技公司的全面产学研合作，将更多的科研技术成果转为生产力，实现双赢发展。</p><p><br/></p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;广东香美农业科技公司董事长陈佳明对公司的基本情况、人才需求、未来规划及校企合作愿景等方面做了基本介绍。她指出，携手汕尾职业技术学院实现产学研合作共建，对于公司发展有着重要意义。希望能依托汕尾职业技术学院的教育优势和创新科研平台，资源共享、优势互补、充分开展各种合作，共同构筑产教融合、联融发展的育人强企模式，打造校企合作标杆院校。未来公司将加大科研经费投入，建设沉香研究院，打造现代沉香产业园，为科研成果转化、专利推广等方面搭建更加广阔的平台，实现共建共赢。</p><p><br/></p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;科研处处长王思荣与广东香美农业科技公司董事长陈佳明在仪式上进行了签约，并共同为“产学研创新实践合作基地”揭牌。</p>','工程学院','2021-12-14 10:52:54');
INSERT INTO `news` (`id`, `title`, `content`, `author`, `time`) VALUES ('27','艺术学院开展“用好红色资源，赓续红色血脉”主题教育活动','<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;红色是中国共产党、中华人民共和国最鲜亮的底色。在我国的广袤大地上，红色资源星罗棋布；在我们党团结带领中国人民进行百年奋斗的伟大历程中，红色血脉代代相传。2021年12月8日，艺术学院开展了“用好红色资源，赓续红色血脉”的主题教育活动，全体预备党员参加了活动，辅导员鄢莎老师为主讲人。<br/></p><p><br/></p><p>&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;<span style="color: var(--el-text-color-regular);">在教育活动中，使每位预备党员深刻理解：每一个历史事件、每一位革命英雄、每一种革命精神、每一件革命文物，都代表着我们党走过的光辉历程、取得的重大成就，展现了我们党的梦想和追求、情怀和担当、牺牲和奉献，汇聚成我们党的红色血脉。</span><br/></p><p><span style="color: var(--el-text-color-regular);"><br/></span></p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;鄢莎老师表示，赓续红色血脉，做到学史明理、学史增信、学史崇德、学史力行，关键是要把握好以下几点：第一，始终坚持科学理论指导；第二，始终坚持理想信念；第三，始终坚持初心使命；第四，始终坚持光荣革命传统；第五，始终坚持推进自我革命。</p><p><br/></p><p>&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;<span style="color: var(--el-text-color-regular);">大家纷纷表示，红色资源是我们党艰辛而辉煌奋斗历程的见证，是最宝贵的精神财富，将会用心用情用力赓续红色血脉。</span><br/></p><p><br/></p><p>&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br/></p><p><br/></p>','艺术学院','2021-12-14 12:04:51');
INSERT INTO `news` (`id`, `title`, `content`, `author`, `time`) VALUES ('28','我校召开帮扶汕尾市城区基础教育高质量发展工作会','<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;为深入贯彻落实省委、省政府、省教育厅关于推动基础教育深化改革高质量发展的意见，推进实施全口径全方位融入式帮扶粤东粤西北地区基础教育工作，推动全省基础教育高质量发展，12月14日，我校在科学楼三楼会议室召开帮扶汕尾市城区基础教育高质量发展工作会。校长蔡昭权教授出席会议并讲话，副校长林炳壮、傅凤龙，学校相关单位负责人参加会议。傅凤龙教授主持会议。<br/></p><p><br/></p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;蔡昭权表示，要充分发挥我校在管理、人才、资源、技术等方面的优势，与汕尾市城区教育局携手帮扶城区中小学在学校管理、党建团建队建、教学质量、师资素质、办学水平等方面实现全面提升。他强调，一是各单位要根据结对帮扶任务分工，落实责任，尽快制定任务完成时间表。二是强化认识，提高站位，要求按照规定的时间节点，高质量完成各项结对帮扶工作。三是责任重大，使命光荣，在结对帮扶的过程中，要立足教育新发展阶段，贯彻教育新发展理念。四是要建立全口径全方位融入式结对帮扶机制和协调沟通互访机制，充分发挥好高校反哺基础教育的职能作用，促进汕尾市城区基础教育高质量发展。<br/></p><p><br/></p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;林炳壮指出，各单位要根据结对帮扶工作任务清单，再细化、再落实，建立帮扶人员和跟岗人员管理保障机制，确保按时完成各项帮扶任务。</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;傅凤龙从提升办学水平、加强校长队伍建设、提升中小学教师综合素质、推进教研协作、推动高等教育帮扶基础教育等五个方面，详细介绍了未来5年涉及的帮扶内容。他对培养优秀中小学校校长、培养名优骨干教师队伍、提高教师队伍能力素质、加强教研队伍建设、提高教师信息技术应用能力、推动教育集团化办学、推动高等教育反哺基础教育等结对帮扶工作任务清单进行具体安排部署，进一步明确各项帮扶任务的责任单位，对下一步如何分阶段分步骤推进结对帮扶工作进行了周密安排和精心指导。</p><p><img src="https://s4.ax1x.com/2021/12/17/TFjLuV.jpg" style="max-width:100%;" contenteditable="false"/></p><p><br/></p>','管理员','2021-12-17 16:37:25');
INSERT INTO `news` (`id`, `title`, `content`, `author`, `time`) VALUES ('29','我校举办党组织书记党建能力提升培训班','<section><section><section><section><section><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font face="黑体" size="3">&nbsp;&nbsp;&nbsp;为深入学习贯彻党的十九届六中全会精神，12月10日至11日，我校举办2021年党组织书记党建能力提升培训班。学校党委委员、副校长林炳壮作开班动员讲话，我校各基层党组织书记和党务干部共25人参加培训。</font></p><p><img src="https://s4.ax1x.com/2021/12/17/TFvFu6.jpg" style="max-width:100%;" contenteditable="false"/></p></section></section></section></section></section><section><font face="黑体" size="3">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;培训为期两天，通过“参观学习+集中授课”两大主线，聚焦党支部书记党建能力提升，以党建引领思想政治建设，发挥学校基层党组织的核心作用，做大做强学校的基层党组织建设，打造汕尾职业技术学院优秀基层党支部与党建人才队伍。</font><br/></section><section><font face="黑体" size="3"><br/></font></section><section><font face="黑体" size="3"><br/></font></section><section>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;培训班邀请广东省委党校历史学博士张雪峰教授和广东省广东轻工职业技术学院艺术设计学院党总支书记李宽松教授分别讲授《十九届六中全会精神解读》《新形势下高职院校基层党建工作方法与经验》，以党的百年历史为主线，分析了百年大党创造的伟大成就，阐述了百年奋斗的历史意义和经验，通过&nbsp;“标杆院系”、“样板党支部”和“双带头人支部书记工作室”的创建立项为实例，分享了新时代背景下以党建为引领创建高质量标杆院系和样板党支部等宝贵经验。</section><p></p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;培训期间，林炳壮副校长带领培训班学员到深圳信息职业技术学院考察学习，在该校周彦兵副校长的带领下参观了党建展厅，深入学习深圳信息职业技术学院在党建领航创建教育部“双高计划”高水平学校和广东省“党建工作示范高校”的历程和成果。随后，到坪山东江纵队纪念馆参观学习，通过了解东江纵队在抗日战争时期，坚持独立自主的游击战争方针，与敌人顽强斗争的历史，破坏敌人交通运输线，营救香港民主人士的故事，再次体会到中华儿女投身革命大无畏的精神。在展厅里，林炳壮副校长带领全体学员重温了入党誓词。</p><p><br/></p><section><section><section><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;本次培训是落实学校党委开展“党史学习”主题教育活动要求，面向我校基层党组织书记开展的一次提高党建能力教育学习活动。进一步加深了对党的十九届六中全会精神的学习领会，深入学习党建理论知识和先进院校的实践经验，对进一步推进我校党建工作和基层党组织建设，全面提升我校党建工作水平打下良好的基础。</p></section></section></section><section><img src="https://s4.ax1x.com/2021/12/17/TFvkDK.jpg" style="max-width:100%;" contenteditable="false"/></section>','管理员','2021-12-17 16:41:20');
INSERT INTO `news` (`id`, `title`, `content`, `author`, `time`) VALUES ('30','我院开展教、学并举，大国工匠为主题的实践观摩课','<section><section><section><section><section><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;为加强教师队伍建设，提高课堂教学质量，发挥优秀教师的示范引领作用，我校教务处近日组织开展了教学观摩课活动。12月8日，我院王有坤老师课程团队进行了一场精彩的示范课。学校领导、各处室负责人、教务处相关人员、我院领导及相关老师参与了听课。</p><p><img src="https://s4.ax1x.com/2021/12/17/TFv4r6.png" style="max-width:100%;" contenteditable="false"/></p></section></section></section></section></section><section><section><section><section><section><section><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;王有坤老师主讲课程 “电路分析基础”，在教学过程中，讲授了“基础电路设计及基尔霍夫定律验证”，课堂中，师生互动频繁，配合默契，课堂气氛一直热烈有序。本次教学王老师以“6S”管理为主线，从思政目标、能力目标、素养目标从发布置任务；学生进行现自行场实操，做到学中做、做中学，充分调动学生学习的积极性并提交作品，老师进行课堂点评；讲授中重视理实结合，有教师操作示范，有学生自行实操、小组练习，做到学中做、做中学，并让同学分享感受，学生参与度极高；培养学生分析问题、解决问题、从事科研及生产的综合能力和大国工匠精神。</p><p><br/></p><section><section><section><section><section><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;此次教学示范观摩课活动的开展，不仅为我院教师搭建了一个实践教学、展示才干的平台，加强了教师间的交流与合作，而且一定程度上推动了课堂教学改革，也在教师群体中形成良好的教学研讨风气，促进了我院教师队伍的整体建设，对我系教研工作具有较大的推动作用</p></section></section></section></section></section><p><img src="https://s4.ax1x.com/2021/12/17/TFvhKx.png" style="max-width:100%;" contenteditable="false"/></p></section></section></section></section></section><section><br/></section></section>','海洋学院','2021-12-17 16:44:44');
INSERT INTO `news` (`id`, `title`, `content`, `author`, `time`) VALUES ('31','喜报！我院学子在第六届粤港澳大湾区IT应用系统开发大赛中荣获佳绩','<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;12月11日下午，第六届粤港澳大湾区IT应用系统开发大赛颁奖典礼在广州举行。大赛共在11座城市设立了12个赛区，报名参赛人数1514人，参赛项目794项，覆盖高校47所，最终39个优秀作品晋级总决赛。我院师生团队经过汕尾赛区选拔赛、粤港澳大湾区总决赛的激烈角逐，最终荣获一等奖1项、最佳应用奖1项、二等奖1项。</p><p><br/></p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;粤港澳大湾区IT应用系统开发大赛是由广州市港澳办、广州市科协、深圳市科协、广州市工信局、共青团广州市委共同指导，由香港青年IT网络、澳门国际科技产业发展协会、粤港澳大湾区科技协同创新联盟共同主办。为做好本届大赛准备工作，指导老师和参赛学生积极备赛。大赛命题发布后，同学们就开始积极调研、分析赛题需求，根据专业技术特长组队，在老师指导下研究学习相关前沿技术，并进行了数月的集中开发。</p><p><br/></p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;此次比赛所取得的优秀成绩是对我院学子创新意识和创新能力的又一次肯定，更体现了我院在创新创业教育水平上的不断提升。通过比赛，提高了学生的实践能力和沟通能力，培养了创业精神和团队协作精神。赛后，师生将针对在大赛中发现的问题积极优化完善作品，立足实际情况创新应用，在比赛方案的基础上更进一步，全方位提升学生的综合素质、学习能力与问题解决能力。</p><p><img src="https://s4.ax1x.com/2021/12/17/TFxlW9.png" style="max-width:100%;" contenteditable="false"/></p>','海洋学院','2021-12-17 16:46:24');
INSERT INTO `news` (`id`, `title`, `content`, `author`, `time`) VALUES ('32','喜报！管理学院篮球队豪取五连胜！','<p style="text-align:center;">11月23日晚上19:00分，在汕尾职业技术学院A区篮球场2号球场的“厚德杯”篮球比赛，第一场比赛由管理学院VS人文学院。</p><section style="text-align:center;"><section><section><section><p>随着主裁判的一声哨响，首场比赛正式拉开帷幕。经过一番如火如荼的激烈比拼后，管理学院以79:54战胜人文学院，拿下第一场比赛的胜利！</p></section></section></section></section><p style="text-align:center;">11月27日傍晚18:30，A区篮球场2号场，管理学院VS经贸学院。</p><p style="text-align:center;">&nbsp;随着一声哨响，比赛正式开始。管理学院率先展开激烈的进攻，一度领先两位数的分差。</p><p style="text-align:center;">而经贸学院也不甘示弱，利用三分球把分差追到5分。双方你追我赶，比分不分上下，最终管理学院以57:45的战胜经贸学院，拿下第二场比赛的胜利！</p><p style="text-align:center;">11月28日傍晚18:30, A区篮球场2号场，管理学院VS艺术学院。</p><p style="text-align:center;">&nbsp;比赛刚开始，我们的球员迅速突破对方的防守，多点开花，打出了一波9-0的小高潮。</p><p style="text-align:center;">在下半场比赛中，我方多次发起凌厉的进攻，不给对手一点追分的机会。</p><p style="text-align:center;">最终在我们连续不断地进攻下比分定格在80:57，拿下第三场比赛的胜利！</p><p style="text-align:center;">&nbsp;11月29日傍晚18:30，A区篮球场2号场，管理学院VS工程学院。</p><p style="text-align:center;">&nbsp;比赛一开始，实力同样强劲的工程学院篮球队就利用战术上的优势始终在比分上领先着我们，但越是强大的对手，我们越是能激发出昂扬的斗志。</p><p style="text-align:center;">在下半场刚开始我们就找到了工程学院战术上的漏洞，并展开凶猛的攻势。最终，哨声响起，比分定格在56:50。我们以6分的分差，险之又险地拿下了第四场比赛的胜利！</p><p style="text-align:center;">12月1日傍晚20:00，A区篮球场2号场，管理学院VS海洋学院。</p><p style="text-align:center;">&nbsp;双方球员进行了友好互动后，比赛正式开始。每一位球员们心怀斗志，我们的进攻后卫在场上以灵活的姿态绕过了一个又一个敌方球员，投进两个三分球！大大鼓舞了士气，再度投入数个三分球，将比分狠狠地拉开。</p><p style="text-align:center;">最后，管理学院的比分定格在了59:48拿下了第五场比赛的胜利！</p><p><img src="https://s4.ax1x.com/2021/12/17/TFzpOx.jpg" style="max-width:100%;" contenteditable="false"/></p>','管理学院','2021-12-17 16:49:12');
INSERT INTO `news` (`id`, `title`, `content`, `author`, `time`) VALUES ('33','艺术学院八名教师获得教育部“1+X”器乐艺术指导师资培训证书及考评员证书','<p style="text-align:center;"><strong>艺术学院八名教师获得教育部“1+X”器乐艺术指导</strong></p><p style="text-align:center;"><strong>师资培训证书及考评员证书</strong></p><p style="text-align:center;">“1+X”证书制度试点工作是国家从战略层面制定的高职教育发展规划，是高职院校探索发展之道。为贯彻落实《国家职业教育改革实施方案》要求和《关于在院校实施“学历证书+若干职业技能等级证书”制度试点方案》《关于推进1+X证书制度试点工作的指导意见》文件精神，于2021年5月完成了器乐艺术指导职业技能等级（初级）试点校的申报工作。我院桑烨等8名教师参加了师资培训，经严格考核评定，顺利结业并获取了考评员资格，刘丰豪老师被评为优秀学员。<img src="https://s4.ax1x.com/2021/12/17/TFzBAU.jpg" contenteditable="false" style="color: var(--el-text-color-regular); font-size: var(--el-dialog-content-font-size); max-width: 100%;"/></p><br/>','艺术学院','2021-12-17 16:51:21');
INSERT INTO `news` (`id`, `title`, `content`, `author`, `time`) VALUES ('34','​诵读红色家书，牢记时代使命','<p data-we-empty-p="" style="text-align:left;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;诵中华经典，抒爱国情怀，2021年12月10日晚，人文学院“诵读红色家书，牢记时代使命”红色家书诵读总决赛在学术报告厅举行。<br/></p><p><br/></p><p style="text-align:left;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;本次诵读大赛分为个人组和团体组两个组别。从今年10月开始，各参赛选手经班级初赛、学院半决赛的层层选拔，最终脱颖而出，进入决赛。&nbsp;</p><p style="text-align:left;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;参赛选手们个个精神抖擞，信心百倍依次上台诵读了红色家书。烽火连三月，家书抵万金。一篇篇红色经典作品荡气回肠，一个个革命故事感人至深。红色经典传播的是对党忠诚、对革命事业的执着、对家国的热爱！一个个传颂的红色经典故事，就是一笔笔宝贵的历史财富。同学们通过声情并茂地诵读，抒发了对党和国家的无限热爱，诚挚的情感感染着在场的师生，富有表现力、感染力的诵读赢得了在场全体师生的阵阵掌声。</p><p data-we-empty-p="" style="text-align:left;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;追寻红色记忆，传承红色精神。此次大赛，是人文学院党史学习教育活动和贯彻学习十九届六中全会精神之一，是对全体师生的一次理想信念教育，以此次活动为契机，让师生感受《红色家书》字里行间的拳拳情义，引导广大师生增强“四个意识”，坚定“四个自信”，做到“两个维护”，把青年学生努力培养成担当民族复兴大任的时代新人，德智体美劳全面发展的社会主义建设者和接班人。</p><p><img src="https://s4.ax1x.com/2021/12/17/Tkpndf.jpg" style="max-width:100%;" contenteditable="false"/></p>','人文学院','2021-12-17 16:58:52');
INSERT INTO `news` (`id`, `title`, `content`, `author`, `time`) VALUES ('35','洒青春之汗水 扬人文之激情','<p style="text-align:center;">运动员们早已按耐不住为班级增光添彩的心情，恨不得比赛马上开始。</p><p style="text-align:center;">看!运动员们正在做着热身活动。他们做得那么认真，生怕因没有拉伸开，影响比赛的成绩。</p><p style="text-align:center;">&nbsp;看!裁判们正在忙碌。他们一丝不苟的检查着场地。医护人员正全神贯注的关注着赛场，随时待命。</p><p style="text-align:center;">观众们更是热情高涨，整齐振奋的口号就来自我们看台的拉拉队。围绕在运动场边的树木，在秋风的频繁光顾下奏鸣出悦耳的树叶的交响曲，仿佛是为了配合场上的拉拉队为奋斗的运动员们加油鼓劲。</p><p><img src="https://s4.ax1x.com/2021/12/17/TkCAbt.jpg" style="max-width:100%;" contenteditable="false"/></p><p><br/></p><p>百米赛跑、接力比赛。运动场上，是矫健的身姿；观众席上，是呐喊与掌声。汕职院人文学子的青春活力此刻展现的淋漓尽致。</p><p>铅球、跳远，也如火如荼地进行着。在流畅的跃动线条下，青春奋发激昂，如大鹏，展翅长空；如蛟龙，畅游四海。</p><p>辅导员:<br/></p><p>&nbsp; &nbsp; &nbsp; &nbsp;一年一次的校运会，是全校的体育盛事，是广大师生展示风采，促进交流的舞台，也是对我校体育工作，师生精神风貌的一次检阅。希望全体运动健儿们能以高昂的斗志和顽强的精神，积极参赛，赛出成绩，赛出风格。为班级争光，为学院争光。</p><p>运动员代表:&nbsp;&nbsp;</p><p>&nbsp; &nbsp; &nbsp;&nbsp; 伏尔泰曾说过：“生命在于运动。”通过参加本次校运会，我体会到了运动的快乐，也深知其中的艰辛与不易。我会在突破挫折和克服困难中朝着自己既定的目标前进，总会有意想不到的收获！</p><p>志愿者：</p><p>&nbsp; “人文荟萃，尽展光辉；和衷共济，所向披靡。”看着运动健儿们在赛场上拼搏，作为幕后工作人员，能替他们解决后顾之忧，我感到非常的高兴，愿他们在本届校运会取得优异的成绩。</p><p>&nbsp; &nbsp; &nbsp; &nbsp;低头是跑道，抬头是梦想。不负韶华，不畏挑战。人生就如同一场慢慢长跑，只有坚持和不懈努力的人，才能赢得最终的胜利。</p><p><br/></p><p><br/></p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2021年11月26日，伴随着一阵阵欢呼声，本次校运会圆满结束啦！振奋人心的时刻永远记在心里，紧张又激烈的比赛让我们意犹未尽。本届运动会已暂时落幕，而我们的精彩永不停止！我们是新时代的逐梦人。我们有着坚强的意志，我们会把更高更强、努力拼搏的体育精神带到我们的学习和生活，我们的明天将会更加精彩！</p><p><br/></p><p><img src="https://s4.ax1x.com/2021/12/17/TkCkDI.jpg" style="max-width:100%;" contenteditable="false"/></p>','人文学院','2021-12-17 17:02:26');
INSERT INTO `news` (`id`, `title`, `content`, `author`, `time`) VALUES ('36','工程学院成功举办第一届“工程杯”数学建模竞赛宣讲会','<p>12月15日，我院在学术报告厅成功举办了第一届“工程杯”数学建模竞赛宣讲会。本次活动由我院陈培辉老师主讲，共有300多名师生参与。</p><p><br/></p><p>首先，刘少锴副院长为本次宣讲会做了致辞，热烈欢迎参与本次宣讲会的全体师生，肯定了我院近三年在数学建模取得的突破以及在各项职业技能竞赛上取得的亮眼成绩，并对到场的全体学生提出殷切期望，希望能积极参与到各项高水平赛事中，始终以高标准严格要求自己，不断提升自我，向着更高的目标迈进。</p><p><br/></p><p><br/></p><section><p>会上，陈培辉老师从全国大学生数学建模竞赛及其参赛情况、近三年我院在数模竞赛的成果积累、第一届“工程杯”数学建模竞赛的准备情况、如何准备数学建模竞赛等多个方面做了精彩的报告。与会学生就数模竞赛的知识储备、专业知识的学习等相关专业问题，与陈培辉老师进行了热烈的讨论，获得了丰富的启发。</p></section><section><p><br/></p><p>本次宣讲会旨在推广我院在全国大学生数学建模竞赛的成功经验，大力推进赛教深度融合，强化“以赛促教、以赛促学、以赛促训、以赛促评”的教学氛围，将各项高水平赛事创新融合到应用型人才培养全过程中，创新应用型人才的培养模式，进一步提速、提质推动我院高水平专业群的建设。</p><p>下来，我院将积极推进各项竞赛准备工作，迎接第一届“工程杯”数学建模竞赛的顺利举办！</p><p><img src="https://s4.ax1x.com/2021/12/17/TkCxLn.jpg" style="max-width:100%;" contenteditable="false"/></p></section>','工程学院','2021-12-17 17:04:46');
INSERT INTO `news` (`id`, `title`, `content`, `author`, `time`) VALUES ('37','1+X大数据应用开发（Python）职业技能等级证书考试在我院顺利举行','<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;为贯彻落实《国家职业教育改革实施方案》，进一步推进1+X证书制度试点工作与专业建设、课程建设、师资队伍建设的有机衔接，进一步完善专业建设，将课证融合落到实处提升学生专业技能。12月5日上午，汕尾职业技术学院举行了1+X大数据应用开发（Python）职业技能等级证书（中级）考试，来自193大数据技术、193计算机应用（人工智能方向）等专业的112名学生参加了考试。<br/></p><p><br/></p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;汕尾职业技术学院考点按照考试的培训评价组织——广东泰迪智能科技股份有限公司《关于做好2021年大数据应用开发（Python）职业技能等级证书考核工作的通知》要求做好考点各项相关工作，包括：1+X考试试点和考点建设、教学与学习相关材料的准备、考生数据采集、物料准备、考务安排、考场布置、监考、巡考等。考试前，工程学院组织相关老师对参考学生进行了考前培训，强化训练实操技能，指导学生积极备考。</p><p><img src="https://s4.ax1x.com/2021/12/17/TkiMBn.jpg" style="max-width:100%;" contenteditable="false"/></p><p><br/></p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;本次1+X考试也得到了泰迪公司的大力支持，公司委派了1+X项目部总监郭青山，1+X项目部产品经理王威翔协助学校进行考场布置、物料准备、设备调试等工作。考试过程中，工作人员分工确、各司其职，严格按照规定流程进行组织，112位考生有序候考、进入考场后在规定的时间内顺利完成了理论和实操的考核任务。</p><p><br/></p><p><br/></p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;上午10时许，在实训楼505还举行了1+X证书考核站点授牌仪式。泰迪公司1+X项目部总监郭青山、1+X项目部产品经理王威翔、教务处处长丁达春、教务处副处长彭强、工程学院党总支书记赵龙海、大数据技术教研室主任等参加了授牌仪式。</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;仪式首先由工程学院党总支书记赵龙海致辞，赵书记对郭青山总监和王威翔经理的到来表示热烈欢迎。教务处处长丁达春对“1+X”证书试点、考点工作进行了解读：第一，“1+X”证书制度是国务院关于职业教育改革的一项具体举措，要对“1+X”证书有全面正确的理解，每个学生应明确个人“X"证书的目标。第二，要做好1+X证书职业技能等级标准与专业人才培养目标的对接。“1+X”考证内容要与与专业课程相对接。校企要继续加强沟通协作，进一步优化课程设置和教学内容，统筹教学组织与实施，深化教学方式方法改革，改善实训条件，为社会培养更多高素质的专业技能型人才。</p><p><img src="https://s4.ax1x.com/2021/12/17/TkiQ7q.jpg" style="max-width:100%;" contenteditable="false"/></p>','工程学院','2021-12-17 17:09:16');

INSERT INTO `plank` (`id`, `title`, `content`, `author`, `time`) VALUES ('11','学习贯彻党的十九届六中全会精神','','管理员','2021-12-14 11:57:28');

INSERT INTO `user` (`id`, `username`, `password`, `nick_name`, `age`, `sex`, `address`, `role`) VALUES ('19','admin','admin','管理员','22','男','学生处','1');
INSERT INTO `user` (`id`, `username`, `password`, `nick_name`, `age`, `sex`, `address`, `role`) VALUES ('20','gongchen','123456','工程学院','20','男','工程学院','2');
INSERT INTO `user` (`id`, `username`, `password`, `nick_name`, `age`, `sex`, `address`, `role`) VALUES ('21','yishu','123456','艺术学院','19','女','艺术学院','2');
INSERT INTO `user` (`id`, `username`, `password`, `nick_name`, `age`, `sex`, `address`, `role`) VALUES ('22','guanli','123456','管理学院','22','女','管理学院','2');
INSERT INTO `user` (`id`, `username`, `password`, `nick_name`, `age`, `sex`, `address`, `role`) VALUES ('23','haiyang','123456','海洋学院','25','男','海洋学院','2');
INSERT INTO `user` (`id`, `username`, `password`, `nick_name`, `age`, `sex`, `address`, `role`) VALUES ('24','jingmao','123456','经贸学院','18','女','经贸学院','2');
INSERT INTO `user` (`id`, `username`, `password`, `nick_name`, `age`, `sex`, `address`, `role`) VALUES ('25','renwen','123456','人文学院','21','女','人文学院','2');

